spring.application.name=urbannest

# ===================================================================
# Database Configuration (MySQL)
# ===================================================================
# Replace 'urbannest_db' with your actual local database schema name
spring.datasource.url=jdbc:mysql://localhost:3306/urbannest_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=MyNewPass123!
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===================================================================
# JPA / Hibernate Configuration
# ===================================================================
# 'update' automatically creates tables or adds new columns without deleting old data

spring.jpa.hibernate.ddl-auto=update

# Shows the generated SQL in your terminal (great for debugging queries)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Ensures Hibernate uses MySQL 8+ optimized SQL generation
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# ===================================================================
# Server & File Upload Configurations
# ===================================================================
server.port=8080

# Sets max file size limit for room images (Default is 1MB, which is too small)
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

cloudinary.cloud-name=dduduxhdt
cloudinary.api-key=475139556537118
cloudinary.api-secret=lUMTxI9zgO0WBal83VT0wHA5t54