spring.application.name=urbannest

# ===================================================================
# Database Configuration (MySQL)
# ===================================================================
# Replace 'urbannest_db' with your actual local database schema name
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===================================================================
# JPA / Hibernate Configuration
# ===================================================================
# 'update' automatically creates tables or adds new columns without deleting old data

spring.jpa.hibernate.ddl-auto=update

# Shows the generated SQL in your terminal (great for debugging queries)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Ensures Hibernate uses MySQL 8+ optimized SQL generation
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# ===================================================================
# Server & File Upload Configurations
# ===================================================================
server.port=8080

# Sets max file size limit for room images (Default is 1MB, which is too small)
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME}
cloudinary.api-key=${CLOUDINARY_API_KEY}
cloudinary.api-secret=${CLOUDINARY_API_SECRET}
